### ISSUE TITLE
Double requirement given in requirements.txt

### ISSUE THREAD

**Issue by TRKBKR** [dragonked2/Egyscan#1]
The requirements.txt file contains a duplicate entry for the "ratelimit" package, leading to an error during the installation process. Resolving this duplication is necessary to ensure the successful installation of dependencies and eliminate the error.

When attempting to install the project's dependencies using the requirements.txt file, the following error is encountered:

` ERROR: Double requirement given: ratelimit (from -r requirements.txt (line 6)) (already in ratelimit==2.2.2 (from -r requirements.txt (line 4)), name='ratelimit')
``

**Comment by dragonked2** [comment]
### **Working on it Thank You For The Quick Notice**
