### ISSUE TITLE
collect_urls_from_file is not definded

### ISSUE THREAD

**Issue by jamatou** [dragonked2/Egyscan#17]
Hi,
First thank you for your effort.
When i add a list of urls i get this error.

collect_urls_from_file is not definded

Thanks,
Jamshid

![error](https://github.com/dragonked2/Egyscan/assets/45011146/91c6d184-d0f0-4be0-a1c0-b834b03d16ce)

**Comment by dragonked2** [comment]
Hello 
and welcome thanks for spotting this issue 

i have figured the issue and the sloution is 
replace this function 
def load_websites_from_file(file_path):
    try:
        with open(file_path, "r") as file:
            websites = file.read().splitlines()
        return websites
    except FileNotFoundError:
        print_error(f"File '{file_path}' not found.")
        return []
        
        with this 
        
        -------------------
        
        def collect_urls_from_file(file_path):
    try:
        with open(file_path, "r") as file:
            websites = file.read().splitlines()
        return websites
    except FileNotFoundError:
        print_error(f"File '{file_path}' not found.")
        return []
        
        and it will work 100% 
        i will now upload the new files 
        thank you again and if you have any other improvements you would like to ask i will be very welcome :)

**Comment by jamatou** [comment]
Thanks for reply.
I gave the list, it colleted the urls but before scan gives following error.

[Error]Error occurred during the scan process: 'module' object is not callable 

![error](https://github.com/dragonked2/Egyscan/assets/45011146/bd4cf189-1dfa-4154-915c-20b289c924b6)
