### ISSUE TITLE
module' object is not callable

### ISSUE THREAD

**Issue by jamatou** [dragonked2/Egyscan#21]
Hi again
I gave the list, it colleted the urls but before scan gives following error.

[Error]Error occurred during the scan process: 'module' object is not callable
![error](https://github.com/dragonked2/Egyscan/assets/45011146/f75f9cf8-b65e-42db-b5f4-b985e1675b3c)

**Comment by dragonked2** [comment]
Hello and thanks for bringing this to our attention 
the module massage error happen only after the crawl&scan steps finished that mean the tool didint find any bugs during the scan 
but will try to check where the error coming from and fix it Thank You Again :)
