### ISSUE TITLE
Errror

### ISSUE THREAD

**Issue by MouhyiHacker** [dragonked2/Egyscan#29]
Before he find bug, and i put url again and he said this,

[Info]Collecting URLs from the target website...
Collecting URLs:   0%|                                                     | 0/1ERROR - Request Exception for URL: http://'https://www.yoti.com/' , Error: HTTPConnectionPool(host="'https", port=80): Max retries exceeded with url: //www.yoti.com/'%20 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f19d6c650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Collecting URLs: |                                                         | 1/0
Found 0 URLs to scan.
[Info]Scanning collected URLs for vulnerabilities...
[Error]Error occurred during the scan process: 'module' object is not callable
Choose an option:
 What i have to do?

**Comment by dragonked2** [comment]
The issue relay on your connection and the block of the website itself not the tool
