### ISSUE TITLE
Tool Stoped

### ISSUE THREAD

**Issue by SamuraiHashira** [dragonked2/Egyscan#8]
The tool keep stooped at the 5% without any results even if I run it on my private server 

![image](https://github.com/dragonked2/Egyscan/assets/68142138/05b9e264-0237-4e14-ac51-67fbc87f325e)

**Comment by dragonked2** [comment]
Hello 
the screen you provided show that the tool is working in collecting urls step
and it takes alot of time based on the website size and pages numbers inside it 
please give it some time 
and keep me updated
